export const theme = {
  color: {
    whiteSmoke: '#fafafa',
    orange: '#d87d4a',
    lightOrange: '#fbaf85',
    lightGray: '#f1f1f1',
    gray: '#d3d3d3',
    white: '#ffffff',
    black: '#191919',
    darkGray: 'rgba(0,0,0,0.5)',
    lightBlack: 'rgba(255,255,255,0.5)',
    inputBorder: '#CFCFCF',
    red: '#CD2C2C',
    granit: 'rgba(255, 255, 255, 0.1)',
    hoverBlack: '#4c4c4c',
    green: '#38A169',
    darkGreen: 'rgba(0, 0, 0, 0.06)',
  },
  font: {
    size: {
      smallText: '13px',
      mediumText: '14px',
      largeText: '15px',
      hugeText: '16px',
      smallHeading: '18px',
      mediumHeading: '28px',
      largeHeading: '40px',
      hugeHeading: '56px',
    },
    weight: {
      regular: '400',
      bold: '700',
    },
  },
  letterSpacing: {
    small: '0.125rem',
    big: '0.625rem',
  },
  lineHeight: '1.7',
  mq: {
    hugePhone: '@media (min-width: 500px)',
    tablet: '@media (min-width: 768px)',
    desktop: '@media (min-width: 1024px)',
  },
};
